sonar.projectKey=getlink-dtd
sonar.projectName=getlink-dtd
sonar.projectVersion=0.1.0

sonar.sources=api-gateway/src/main,auth-service/src/main,link-service/src/main,frontend/src
sonar.tests=api-gateway/src/test,auth-service/src/test,link-service/src/test,frontend/tests
sonar.java.binaries=api-gateway/target/classes,auth-service/target/classes,link-service/target/classes
sonar.junit.reportPaths=api-gateway/target/surefire-reports,auth-service/target/surefire-reports,link-service/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=api-gateway/target/site/jacoco/jacoco.xml,auth-service/target/site/jacoco/jacoco.xml,link-service/target/site/jacoco/jacoco.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.coverage.exclusions=frontend/src/**/*.tsx
sonar.sourceEncoding=UTF-8
